version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "maven"
    directory: "/train-history-backend"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "maven"
    directory: "/train-history-updater"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/train-history-web"
    schedule:
      interval: "daily"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
