/*
 * This file is generated by jOOQ.
*/
package fi.livi.trainhistorybackend.entities;


import jakarta.persistence.Entity;
import java.io.Serializable;


@Entity
public class Train extends JsonEntity implements Serializable {
    public Train() {
    }
}
