services:
  rail_history_mysql:
    image: mysql:8.0.42-debian
    restart: unless-stopped
    #platform: linux/amd64
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=rail_history
      - MYSQL_PASSWORD=rail_pass123
      - MYSQL_DATABASE=trainhistoryjson
    ports:
      - "3306:3306"
    volumes:
      - rail_history_mysql_data:/var/lib/mysql
    networks:
      - rail_history_network

  rail_history_flyway:
    build: ./Flyway
    volumes:
      - "../train-history-updater/src/main/resources/db/migration:/flyway/sql"
    command: -url=jdbc:mysql://rail_history_mysql -schemas=trainhistoryjson -user=rail_history -password=rail_pass123 -connectRetries=10 migrate
    networks:
      - rail_history_network
    depends_on:
      - rail_history_mysql

volumes:
  rail_history_mysql_data:

networks:
  rail_history_network:
    driver: bridge
