/*
 * This file is generated by jOOQ.
*/
package fi.livi.trainhistoryupdater.entities;


import java.io.Serializable;
import jakarta.persistence.Entity;


@Entity
public class Train extends JsonEntity implements Serializable {
    public Train() {
    }
}
