name: 'Mirror repo to public'
on:
  push:
    branches:
      - master
jobs:
  mirror-action:
    runs-on: ubuntu-latest
    steps:
      - name: mirror
        uses: tmfg/digitraffic-actions@mirror/v2
        with:
          mirror-repo: git@github.com:tmfg/digitraffic-rail-history
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
      - name: Notify Slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: FAILED Rail-history Mirror
          fields: repo, job, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
