name: 'Mirror repo to public'
on:
  push:
    branches:
      - master
jobs:
  mirror-action:
    if: github.repository != 'tmfg/digitraffic-rail-history'
    runs-on: ubuntu-24.04
    steps:
      - name: mirror
        uses: tmfg/digitraffic-actions@mirror/v2
        with:
          mirror-repo: git@github.com:tmfg/digitraffic-rail-history
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
      - name: Notify Slack
        if: failure()
        uses: tmfg/digitraffic-actions@slack-notify/v1
        with:
          status: failure
          text: FAILED Rail-history Mirror
          fields: repo, job, took
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
