name: 'Mirror repo to public'
on:
  push:
    branches:
      - master
jobs:
  mirror-action:
    if: github.repository != 'tmfg/digitraffic-rail-history'
    runs-on: ubuntu-26.04
    steps:
      - name: mirror
        uses: tmfg/digitraffic-actions@80082556de86d5f8643e40312ae9f4cdfcbd4b82 # mirror/v3
        with:
          mirror-repo: git@github.com:tmfg/digitraffic-rail-history
          ssh-private-key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}
      - name: Notify Slack
        if: failure()
        uses: tmfg/digitraffic-actions@dd6f974ac0e0fe24e70e70487de009a669c0d704 # slack-notify/v1
        with:
          status: failure
          text: FAILED Rail-history Mirror
          fields: repo, job, took
          webhook-url: ${{ secrets.SLACK_ALARMS_WEBHOOK_URL }}
